JOIN_MESSAGE:
  - "&7&m-------------------------------------------------"
  - "  &d               Server Name"
  - ""
  - "  ● &dWebsite: &fhttps://example.com"
  - "  ● &dDiscord: &fhttps://example.com"
  - "  ● &dStore: &fhttps://example.com"
  - "  ● &dTwitter: &fhttps://example.com"
  - "&7&m-------------------------------------------------"